# Generated by Django 5.2.7 on 2025-11-24 23:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_financemanagement'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='financemanagement',
            name='tax_percentage',
        ),
        migrations.AddField(
            model_name='financemanagement',
            name='tax_amount',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12),
        ),
        migrations.AlterField(
            model_name='financemanagement',
            name='child_allowance',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=2),
        ),
        migrations.AlterField(
            model_name='financemanagement',
            name='spouse_allowance',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=2),
        ),
    ]
