# Generated by Django 5.2.7 on 2025-11-24 23:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_remove_financemanagement_tax_percentage_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='financemanagement',
            name='child_allowance',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='financemanagement',
            name='spouse_allowance',
            field=models.IntegerField(default=0),
        ),
    ]
