# Generated by Django 6.0rc1 on 2025-11-26 02:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_alter_financemanagement_child_allowance_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='financemanagement',
            name='gross_salary',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12),
        ),
        migrations.AddField(
            model_name='financemanagement',
            name='net_salary',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12),
        ),
    ]
