# Generated by Django 6.0rc1 on 2025-11-26 04:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0007_employee_bankaccount'),
    ]

    operations = [
        migrations.AddField(
            model_name='employee',
            name='identity_number',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
        migrations.AddField(
            model_name='employee',
            name='tax_number',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
    ]
