# Generated by Django 6.0rc1 on 2025-11-26 08:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0009_sitesetting'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='financemanagement',
            name='bpjs_employment_percentage',
        ),
        migrations.RemoveField(
            model_name='financemanagement',
            name='bpjs_health_percentage',
        ),
        migrations.RemoveField(
            model_name='financemanagement',
            name='gross_salary',
        ),
        migrations.RemoveField(
            model_name='financemanagement',
            name='net_salary',
        ),
        migrations.RemoveField(
            model_name='financemanagement',
            name='overtime_hours',
        ),
        migrations.RemoveField(
            model_name='financemanagement',
            name='receivable_amount',
        ),
        migrations.RemoveField(
            model_name='financemanagement',
            name='tax_amount',
        ),
        migrations.AddField(
            model_name='financemanagement',
            name='enable_bpjs_employment',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='financemanagement',
            name='enable_bpjs_health',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='financemanagement',
            name='enable_tax',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='financemanagement',
            name='is_active',
            field=models.BooleanField(default=False),
        ),
    ]
