# Generated by Django 6.0rc1 on 2025-11-26 08:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0011_overtimelog'),
    ]

    operations = [
        migrations.AddField(
            model_name='financemanagement',
            name='bpjs_employment_rate_percentage',
            field=models.DecimalField(decimal_places=2, default=2, max_digits=5),
        ),
        migrations.AddField(
            model_name='financemanagement',
            name='bpjs_health_rate_percentage',
            field=models.DecimalField(decimal_places=2, default=1, max_digits=5),
        ),
    ]
