# Generated by Django 6.0rc1 on 2025-11-26 09:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0012_financemanagement_bpjs_employment_rate_percentage_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='financemanagement',
            name='tax_rate_percentage',
            field=models.DecimalField(decimal_places=2, default=1, max_digits=5),
        ),
    ]
