# Generated by Django 6.0rc1 on 2025-11-27 07:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0013_financemanagement_tax_rate_percentage'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserOvertimeLog',
            fields=[
            ],
            options={
                'verbose_name': 'User Overtime Log',
                'verbose_name_plural': 'User Overtime Logs',
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('api.overtimelog',),
        ),
        migrations.AddField(
            model_name='overtimelog',
            name='paid_date',
            field=models.DateField(blank=True, default=None, null=True),
        ),
    ]
