# Generated by Django 5.2.8 on 2025-12-02 23:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0014_userovertimelog_overtimelog_paid_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='salaryslip',
            name='reimburse_total_amount',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12),
        ),
    ]
