# Generated by Django 5.2.8 on 2025-12-07 16:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0015_salaryslip_reimburse_total_amount'),
    ]

    operations = [
        migrations.AlterField(
            model_name='financemanagement',
            name='tax_rate_percentage',
            field=models.DecimalField(decimal_places=2, default=1, max_digits=12),
        ),
    ]
