# Generated by Django 5.2.8 on 2025-12-27 08:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0016_alter_financemanagement_tax_rate_percentage'),
    ]

    operations = [
        migrations.RenameField(
            model_name='salaryslip',
            old_name='reimburse_total_amount',
            new_name='monthly_reimburse',
        ),
    ]
