# Generated by Django 5.2.8 on 2025-12-28 01:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0017_rename_reimburse_total_amount_salaryslip_monthly_reimburse'),
    ]

    operations = [
        migrations.AlterField(
            model_name='salaryslip',
            name='gross_salary',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=16),
        ),
        migrations.AlterField(
            model_name='salaryslip',
            name='monthly_reimburse',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=16),
        ),
        migrations.AlterField(
            model_name='salaryslip',
            name='net_salary',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=16),
        ),
    ]
