# Generated by Django 5.2.8 on 2025-12-28 01:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0019_alter_salaryslip_gross_salary_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='salaryslip',
            name='bpjs_employment',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=16),
        ),
        migrations.AlterField(
            model_name='salaryslip',
            name='tax_amount',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12),
        ),
    ]
